/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        'bg-base': 'var(--bg-base)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-raised': 'var(--bg-raised)',
        'fg-primary': 'var(--fg-primary)',
        'fg-secondary': 'var(--fg-secondary)',
        'fg-tertiary': 'var(--fg-tertiary)',
        'fg-inverse': 'var(--fg-inverse)',
        'border-base': 'var(--border-base)',
        'border-strong': 'var(--border-strong)',
        'border-accent': 'var(--border-accent)',
        'accent-primary': 'var(--accent-primary)',
        'accent-primary-dim': 'var(--accent-primary-dim)',
        'semantic-success': 'var(--semantic-success)',
        'semantic-warning': 'var(--semantic-warning)',
        'semantic-error': 'var(--semantic-error)',
        'semantic-info': 'var(--semantic-info)',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'IBM Plex Mono', 'Menlo', 'Consolas', 'monospace'],
        sans: ['IBM Plex Sans', '-apple-system', 'Segoe UI', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
      },
      spacing: {
        'px': '1px',
        '0.5': '2px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
      },
      borderRadius: {
        none: '0',
        xs: '2px',
        sm: '4px',
      },
      transitionDuration: {
        instant: '0ms',
        fast: '100ms',
        normal: '150ms',
        slow: '200ms',
      },
      transitionTimingFunction: {
        snap: 'cubic-bezier(0.2, 0, 0, 1)',
        'in-sharp': 'cubic-bezier(0.4, 0, 1, 1)',
      },
    },
  },
  plugins: [],
};
